site:
  title: Docs Site
  start_page: bpmd::index.adoc
content:
  sources:
  - url: ../bpmn-parser/
    branches: HEAD
    start_path: docs-site
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
